# Generated by Django 5.0.6 on 2025-04-25 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_addition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=25)),
                ('category', models.CharField(choices=[('electronics', 'Electronics'), ('fashion', 'Fashion'), ('home_appliance', 'HomeAppliances'), ('books', 'Books'), ('beauty', 'Beauty')], max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('price', models.CharField(max_length=20)),
                ('quantity', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
