# Generated by Django 5.0.6 on 2025-04-25 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0002_tb_addition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tb_addition',
            name='image',
        ),
        migrations.AddField(
            model_name='tb_addition',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='static/image/'),
        ),
    ]
