# Generated by Django 5.0.6 on 2025-04-30 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0003_remove_tb_addition_image_tb_addition_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_addition',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
