# Generated by Django 5.0.6 on 2025-05-15 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0006_blah_remove_profile_user_delete_tb_addition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blah',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('fashion', 'Fashion'), ('home_appliance', 'HomeAppliances'), ('books', 'Books'), ('jewellery', 'Jewellery')], max_length=50),
        ),
    ]
