# Generated by Django 5.0.6 on 2025-05-09 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userlogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=25)),
                ('confirmpassword', models.CharField(max_length=25)),
            ],
        ),
    ]
