# Generated by Django 5.0.6 on 2025-05-15 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=20)),
                ('price', models.PositiveBigIntegerField(max_length=20)),
                ('quantity', models.PositiveIntegerField(max_length=20)),
                ('total', models.IntegerField(max_length=20)),
                ('address', models.TextField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/image/')),
            ],
        ),
        migrations.AlterField(
            model_name='userlogin',
            name='email',
            field=models.EmailField(max_length=25),
        ),
    ]
